version: '3.8'

services:
  zabbix-db:
    image: postgres:15-alpine
    container_name: zabbix-db
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_net
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-7.0-latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_password
    networks:
      - db_net
      - monitor_net
      - webhook_net
    depends_on:
      - zabbix-db
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-7.0-latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_password
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Paris
    networks:
      - db_net
      - api_net
      - frontend_net
    depends_on:
      - zabbix-db
      - zabbix-server
    restart: always

volumes:
  pgdata:

networks:
  db_net:
    driver: bridge
    internal: true
  monitor_net:
    external: true
  webhook_net:
    external: true
  api_net:
    external: true
  frontend_net:
    external: true
