FROM zabbix/zabbix-web-nginx-pgsql:ubuntu-7.0-latest

ENV DB_SERVER_HOST=zabbix-db \
    POSTGRES_DB=zabbix \
    POSTGRES_USER=zabbix \
    POSTGRES_PASSWORD=zabbix_password \
    ZBX_SERVER_HOST=zabbix-server \
    PHP_TZ=Europe/Paris

EXPOSE 8080
